/**
 * Structural lint over the rendered DOM.
 *
 * `design-lint.ts` reads CSS text, which is the right tool for "this rule
 * should not exist" but blind to "this page used the right rules too many
 * times". Card saturation, repeated layouts, accent overuse and badge
 * clutter are all properties of the *output*, not of any single
 * declaration, so they need the document.
 *
 * Parsing is done with a small tag scanner rather than a DOM library: the
 * markup is Forma's own, generated by React, so it is well-formed by
 * construction, and this keeps the check available inside `forma build`
 * without a browser.
 */

export interface DomLintFinding {
  rule: string;
  message: string;
}

interface Element {
  tag: string;
  classes: string[];
  attrs: Record<string, string>;
  depth: number;
}

const VOID_TAGS = new Set([
  "area", "base", "br", "col", "embed", "hr", "img", "input",
  "link", "meta", "param", "source", "track", "wbr",
]);

/** Extracts the body's elements with their nesting depth, in document order. */
export function scanElements(html: string): Element[] {
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*)<\/body>/);
  const body = bodyMatch?.[1] ?? html;
  // Style and script bodies contain angle brackets that are not markup.
  const source = body
    .replace(/<style[\s\S]*?<\/style>/g, "")
    .replace(/<script[\s\S]*?<\/script>/g, "");

  const elements: Element[] = [];
  const tagRegex = /<(\/?)([a-zA-Z][\w-]*)([^>]*?)(\/?)>/g;
  let depth = 0;
  let match: RegExpExecArray | null;
  while ((match = tagRegex.exec(source)) !== null) {
    const closing = match[1] === "/";
    const tag = (match[2] ?? "").toLowerCase();
    const rawAttrs = match[3] ?? "";
    const selfClosing = match[4] === "/" || VOID_TAGS.has(tag);

    if (closing) {
      depth = Math.max(0, depth - 1);
      continue;
    }
    const attrs: Record<string, string> = {};
    const attrRegex = /([\w:-]+)\s*=\s*"([^"]*)"/g;
    let attr: RegExpExecArray | null;
    while ((attr = attrRegex.exec(rawAttrs)) !== null) {
      attrs[(attr[1] ?? "").toLowerCase()] = attr[2] ?? "";
    }
    elements.push({
      tag,
      classes: (attrs["class"] ?? "").split(/\s+/).filter(Boolean),
      attrs,
      depth,
    });
    if (!selfClosing) depth += 1;
  }
  return elements;
}

/** Class names that put a block on a raised surface. */
const CARD_CLASS = /(^|-)(card|panel|tile|surface|frame)$|^(status-header|metric)$|__frame$/;

function isCard(element: Element): boolean {
  return element.classes.some((cls) => CARD_CLASS.test(cls));
}

/**
 * AI-authored layouts put everything in a rounded box. Past roughly a third
 * of the page, cards stop creating structure and start flattening it:
 * when every section is raised, none of them is.
 */
function findCardSaturation(elements: Element[]): DomLintFinding[] {
  const sections = elements.filter((el) => el.tag === "section");
  if (sections.length < 4) return [];
  const carded = sections.filter((section, index) => {
    const next = sections[index + 1];
    const end = next ? elements.indexOf(next) : elements.length;
    return elements.slice(elements.indexOf(section), end).some(isCard);
  });
  const ratio = carded.length / sections.length;
  if (ratio <= 0.35) return [];
  return [
    {
      rule: "card-saturation",
      message: `${carded.length} of ${sections.length} sections (${Math.round(ratio * 100)}%) sit on a raised surface. Past ~35% the cards stop creating hierarchy and flatten it.`,
    },
  ];
}

/** A card inside a card is depth for its own sake; the inner one reads as noise. */
function findNestedSurfaces(elements: Element[]): DomLintFinding[] {
  const findings: DomLintFinding[] = [];
  const stack: Element[] = [];
  for (const element of elements) {
    while (stack.length > 0 && (stack[stack.length - 1]?.depth ?? 0) >= element.depth) stack.pop();
    if (isCard(element)) {
      if (stack.some(isCard)) {
        findings.push({
          rule: "nested-surface",
          message: `"${element.classes.join(".")}" is a raised surface inside another raised surface.`,
        });
      }
      stack.push(element);
    }
  }
  return findings;
}

/** Three sections in a row with the same block class read as a template. */
function findLayoutRepetition(elements: Element[]): DomLintFinding[] {
  const blockClasses = elements
    .filter((el) => el.tag === "section")
    .map((el) => el.classes.find((cls) => cls.startsWith("blk-")) ?? "");
  const findings: DomLintFinding[] = [];
  let run = 1;
  for (let i = 1; i < blockClasses.length; i += 1) {
    if (blockClasses[i] && blockClasses[i] === blockClasses[i - 1]) {
      run += 1;
      if (run === 4) {
        findings.push({
          rule: "layout-repetition",
          message: `4 or more consecutive "${blockClasses[i]}" sections. Vary the block or merge them; an unbroken run reads as a template.`,
        });
      }
      continue;
    }
    run = 1;
  }
  return findings;
}

/**
 * Badges are the cheapest way to make something look considered, which is
 * why they multiply. Past a dozen the page is a field of pills and none of
 * them signals anything.
 */
function findPillOveruse(elements: Element[]): DomLintFinding[] {
  const PILL = /(badge|flag|tag|chip|pill)/;
  const count = elements.filter((el) => el.classes.some((cls) => PILL.test(cls))).length;
  if (count <= 12) return [];
  return [
    {
      rule: "pill-overuse",
      message: `${count} badge/flag elements on one page. Past a dozen they stop marking anything out.`,
    },
  ];
}

/** A hover affordance on something that cannot be clicked promises an action that is not there. */
function findFalseInteractivity(html: string): DomLintFinding[] {
  const styleMatch = html.match(/<style>([\s\S]*?)<\/style>/);
  // The @font-face rules carry ~120KB of base64 with no braces in it. A
  // selector pattern of `[^{}]+` backtracks across that whole run at every
  // position, which turned this one rule into 20 seconds per file. Dropping
  // the font block and bounding the selector length keeps it linear.
  const css = (styleMatch?.[1] ?? "").replace(/@font-face\s*\{[^}]*\}/g, "");
  const findings: DomLintFinding[] = [];
  const hoverRegex = /([^{}]{1,200}):hover[^{}]{0,200}\{([^}]*)\}/g;
  let match: RegExpExecArray | null;
  while ((match = hoverRegex.exec(css)) !== null) {
    const selector = (match[1] ?? "").trim();
    if (selector.includes("@")) continue;
    // Anything genuinely interactive, plus the details/summary disclosure.
    if (/\b(a|button|summary|input|select|textarea|label)\b|\[href|\[tabindex|__option|toc|copy|toggle/.test(selector)) {
      continue;
    }
    findings.push({
      rule: "false-interactivity",
      message: `"${selector.slice(0, 60)}" has a hover treatment but is not an interactive element.`,
    });
  }
  return findings;
}

/** A claim marked verified must point at something. Mirrors the planner check at the DOM level. */
function findUnbackedVerifiedClaims(elements: Element[]): DomLintFinding[] {
  const findings: DomLintFinding[] = [];
  elements.forEach((element, index) => {
    if (element.attrs["data-confidence"] !== "verified") return;
    // Look ahead inside the same section for a provenance list.
    const rest = elements.slice(index, index + 60);
    const hasSource = rest.some((el) => el.classes.includes("blk-source-note"));
    if (hasSource) return;
    findings.push({
      rule: "verified-claim-without-evidence",
      message: "a block marked verified renders no source list.",
    });
  });
  return findings;
}


/**
 * Three long prose blocks in a row is a wall. The reader has nothing to
 * anchor on and the artifact has stopped doing the one thing it exists for.
 */
function findProseRun(elements: Element[]): DomLintFinding[] {
  const blocks = elements
    .filter((el) => el.tag === "section")
    .map((el) => el.classes.find((cls) => cls.startsWith("blk-")) ?? "");
  const PROSE = new Set(["blk-prose", "blk-summary", "blk-narrative", "blk-appendix"]);
  let run = 0;
  for (const block of blocks) {
    run = PROSE.has(block) ? run + 1 : 0;
    if (run === 4) {
      return [
        {
          rule: "prose-run",
          message:
            "4 consecutive prose-only sections. Break the run with a figure, a list, or a finding.",
        },
      ];
    }
  }
  return [];
}

/**
 * A heading with almost nothing under it is a heading that should have been
 * a sentence, and it leaves the table of contents promising more than the
 * section delivers.
 */
function findOrphanHeadings(html: string): DomLintFinding[] {
  const findings: DomLintFinding[] = [];
  const sectionRegex = /<section[^>]*class="section (blk-[\w-]+)[^"]*"[^>]*>([\s\S]*?)<\/section>/g;
  let match: RegExpExecArray | null;
  while ((match = sectionRegex.exec(html)) !== null) {
    const blockClass = match[1] ?? "";
    const inner = match[2] ?? "";
    if (!/<h[1-4][\s>]/.test(inner)) continue;
    const text = inner.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
    const headingText = (inner.match(/<h[1-4][^>]*>([\s\S]*?)<\/h[1-4]>/)?.[1] ?? "")
      .replace(/<[^>]+>/g, "")
      .trim();
    const bodyLength = text.length - headingText.length;
    // A cover or status header is a heading by design and carries no body.
    if (/blk-(cover|status-header|thesis|env-selector|version-note)/.test(blockClass)) continue;
    if (bodyLength >= 40) continue;
    findings.push({
      rule: "orphan-heading",
      message: `"${headingText.slice(0, 40)}" has ${bodyLength} characters of content under it.`,
    });
  }
  return findings;
}

export function lintDom(html: string): DomLintFinding[] {
  const elements = scanElements(html);
  return [
    ...findCardSaturation(elements),
    ...findNestedSurfaces(elements),
    ...findLayoutRepetition(elements),
    ...findPillOveruse(elements),
    ...findFalseInteractivity(html),
    ...findUnbackedVerifiedClaims(elements),
    ...findProseRun(elements),
    ...findOrphanHeadings(html),
  ];
}
