import { copyFile, mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { renderSpecFileToDir } from "../renderer/render.js";

const ARTIFACTS = [
  {
    id: "dashboard",
    direction: "Signal Grid",
    promise: "State, movement, drivers, and action — led by numbers and charts.",
  },
  {
    id: "report",
    direction: "Editorial Brief",
    promise: "A conclusion-first argument with evidence, alternatives, and risk.",
  },
  {
    id: "manual",
    direction: "Guided Path",
    promise: "A navigable procedure with prerequisites, checks, and recovery.",
  },
  {
    id: "advanced",
    direction: "Decision Room",
    promise: "Claims, counterclaims, simulation, dissent, and a durable decision.",
  },
] as const;

export interface BuildPagesOptions {
  outDir: string;
  sourceRoot?: string;
}

export async function buildPages(options: BuildPagesOptions): Promise<void> {
  const sourceRoot = path.resolve(options.sourceRoot ?? process.cwd());
  const outDir = path.resolve(options.outDir);

  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });
  await mkdir(path.join(outDir, "_assets"), { recursive: true });

  for (const artifact of ARTIFACTS) {
    await renderSpecFileToDir(
      path.join(sourceRoot, "examples", artifact.id, "forma.spec.json"),
      path.join(outDir, artifact.id),
    );
    await copyFile(
      path.join(sourceRoot, "docs", "images", "artifacts", `${artifact.id}.png`),
      path.join(outDir, "_assets", `${artifact.id}.png`),
    );
  }

  await Promise.all([
    writeFile(path.join(outDir, "index.html"), galleryHtml(), "utf-8"),
    writeFile(path.join(outDir, ".nojekyll"), "", "utf-8"),
  ]);
}

function galleryHtml(): string {
  const cards = ARTIFACTS.map(
    (artifact, index) => `
      <article class="artifact" style="--series: var(--chart-${(index % 4) + 1})">
        <div class="artifact__preview">
          <img src="./_assets/${artifact.id}.png" alt="" loading="lazy" />
        </div>
        <div class="artifact__body">
          <p class="artifact__type">${artifact.id}</p>
          <h2>${artifact.direction}</h2>
          <p>${artifact.promise}</p>
          <a href="./${artifact.id}/index.html">Open real HTML <span aria-hidden="true">→</span></a>
        </div>
      </article>`,
  ).join("");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Forma artifact gallery</title>
<meta name="description" content="Open the four real HTML artifacts generated by Forma." />
<meta name="color-scheme" content="light dark" />
<style>
  :root {
    color-scheme: light dark;
    --canvas: #FFFFFF;
    --surface: #F3F3F3;
    --text: #333333;
    --muted: #616161;
    --border: #D4D4D4;
    --accent: #006AB1;
    --chart-1: #0070C1;
    --chart-2: #267F99;
    --chart-3: #795E26;
    --chart-4: #AF00DB;
    font-family: ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--canvas); color: var(--text); }
  a { color: var(--accent); }
  header, main, footer { width: min(100% - 2rem, 90rem); margin-inline: auto; }
  header { padding-block: 5rem 3rem; border-block-end: 1px solid var(--border); }
  .eyebrow { margin: 0 0 1rem; color: var(--accent); font: 600 0.75rem/1.2 ui-monospace, monospace; letter-spacing: 0.08em; text-transform: uppercase; }
  h1 { margin: 0; max-width: 13ch; font-size: clamp(3rem, 9vw, 7rem); line-height: 0.92; letter-spacing: -0.06em; }
  .lede { max-width: 42rem; margin: 2rem 0 0; color: var(--muted); font-size: 1.125rem; line-height: 1.65; }
  .palette { display: inline-flex; gap: 0.5rem; margin-block-start: 1.5rem; padding: 0.45rem 0.65rem; border: 1px solid var(--border); border-radius: 0.25rem; font: 600 0.75rem/1 ui-monospace, monospace; }
  main { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 1.5rem; padding-block: 3rem 5rem; }
  .artifact { min-width: 0; border: 1px solid var(--border); background: var(--surface); }
  .artifact__preview { position: relative; height: 24rem; overflow: hidden; border-block-end: 4px solid var(--series); background: var(--canvas); }
  .artifact__preview img { width: 100%; height: 100%; object-fit: cover; object-position: top left; display: block; }
  .artifact__body { padding: 1.5rem; }
  .artifact__type { display: flex; align-items: center; gap: 0.5rem; margin: 0 0 0.5rem; color: var(--text); font: 600 0.75rem/1 ui-monospace, monospace; text-transform: uppercase; letter-spacing: 0.08em; }
  .artifact__type::before { content: ""; inline-size: 0.75rem; block-size: 0.25rem; background: var(--series); }
  .artifact h2 { margin: 0; font-size: 1.75rem; letter-spacing: -0.03em; }
  .artifact__body > p:not(.artifact__type) { min-height: 3.5rem; color: var(--muted); line-height: 1.55; }
  .artifact a { font-weight: 650; text-decoration: none; }
  .artifact a:hover { text-decoration: underline; text-underline-offset: 0.2em; }
  footer { padding-block: 1.5rem 3rem; border-block-start: 1px solid var(--border); color: var(--muted); font-size: 0.875rem; }
  @media (prefers-color-scheme: dark) {
    :root {
      --canvas: #1E1E1E;
      --surface: #252526;
      --text: #CCCCCC;
      --muted: #969696;
      --border: #3C3C3C;
      --accent: #3794FF;
      --chart-1: #4FC1FF;
      --chart-2: #4EC9B0;
      --chart-3: #DCDCAA;
      --chart-4: #C586C0;
    }
  }
  @media (max-width: 900px) {
    header { padding-block-start: 3rem; }
    main { grid-template-columns: 1fr; }
    .artifact__preview { height: 17rem; }
  }
</style>
</head>
<body>
  <header>
    <p class="eyebrow">Forma · real rendered outputs</p>
    <h1>Four forms for complex work.</h1>
    <p class="lede">Each capture links to the actual self-contained HTML generated from the repository's current example spec.</p>
    <span class="palette">VS Code Light+ / Dark+</span>
  </header>
  <main>${cards}</main>
  <footer>Built from the current Forma specs on every push to main.</footer>
</body>
</html>`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const outDir = process.argv[2] ?? "dist/pages";
  await buildPages({ outDir });
  console.log(`forma pages: built ${path.resolve(outDir)}`);
}
